require("dotenv").config();

module.exports = [
  {
    id: 0,
    img: "rectangle1.jpg",
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: false,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 1,
    img: "rectangle2.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 3,
    new: true,
    sale: false,
    exist: true,
    bestSeller: true,
  },
  {
    id: 2,
    img: "rectangle3.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: false,
    sale: true,
    exist: true,
    bestSeller: false,
  },
  {
    id: 3,
    img: "rectangle4.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 4,
    new: false,
    sale: false,
    exist: true,
    bestSeller: true,
  },
  {
    id: 4,
    img: "rectangle1.jpg",
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 5,
    img: "rectangle2.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 6,
    img: "rectangle3.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: true,
    sale: true,
    exist: true,
    bestSeller: false,
  },
  {
    id: 7,
    img: "rectangle4.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 8,
    img: "rectangle5.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: false,
  },
  {
    id: 9,
    img: "rectangle1.jpg",
    title: "Փոքրիկ Նվերի Տուփ",
    originalPrice: 300,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: false,
  },
  {
    id: 10,
    img: "rectangle2.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 11,
    img: "rectangle3.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 10000,
    salePrice: 9000,
    rating: 5,
    new: true,
    sale: true,
    exist: true,
    bestSeller: true,
  },
  {
    id: 12,
    img: "rectangle4.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 13,
    img: "rectangle5.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: false,
    bestSeller: true,
  },
  {
    id: 14,
    img: "rectangle4.jpg",
    title: "Օծանելիք - Դիոր",
    originalPrice: 6000,
    salePrice: null,
    rating: 5,
    new: true,
    sale: false,
    exist: true,
    bestSeller: false,
  },
  {
    id: 15,
    img: "rectangle5.jpg",
    title: "Թեյի Բաժակ",
    originalPrice: 4000,
    salePrice: null,
    rating: 5,
    new: false,
    sale: false,
    exist: false,
    bestSeller: false,
  },
];
